source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'font-awesome-sass', '~> 4.3.0'
gem "autoprefixer-rails", '~> 5.1'
gem 'rack-streaming-proxy', '~> 2.0'
gem 'fog', '~>1.20'
gem 'asset_sync', '~> 1.1'
gem 'figaro', '~> 1.1'
gem 'compass-rails', '>= 2.0.4'
gem 'rails_12factor', '~> 0.0.3'
gem 'pg', '~> 0.18'
gem 'therubyracer', '~> 0.12'
gem 'sass-rails', '<= 5.0.1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'modernizr-mixin', '~> 3.0'
gem 'browserify-rails', '~> 0.8.1'
gem 'sass-json-vars', '~> 0.3.2'

group :development, :test do
  gem 'pry'
  gem 'pry-remote'
  gem 'web-console', '~> 2.0'
  gem 'quiet_assets'
  gem 'spring'
  gem 'rack-cors'
end
